services:
  topspeed-server:
    build: .
    image: topspeed-server:2026.4.13.2
    restart: unless-stopped
    environment:
      TOPSPEED_PORT: "28630"
      TOPSPEED_MAX_PLAYERS: "32"
      TOPSPEED_LOG_LEVEL: "info"
      # TOPSPEED_MOTD: "Welcome to TopSpeed"
    ports:
      - "28630:28630/udp"
      - "28631:28631/udp"
    volumes:
      - topspeed-data:/app/settings

volumes:
  topspeed-data:
